# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCentauro():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_centauro(self):
    self.driver.get("https://centauro.eurocontrol.es/centauro/index.php")
    self.driver.set_window_size(848, 990)
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("JoGiro")
    self.driver.find_element(By.NAME, "strPassword").click()
    self.driver.find_element(By.NAME, "strPassword").click()
    self.driver.find_element(By.NAME, "strPassword").send_keys("skXuBXyX")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(1) .nav-link-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dt-button:nth-child(2) > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dt-button:nth-child(4) > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.close()
  
